### ISSUE TITLE
migration DTSD to shadow ?

### ISSUE THREAD

**Issue by elstringer** [doomsider/shadow#3]
hello, a simple question ! how the DTSD migrated data to the database shadow ?

I did my tests currently on a vm based on archlinux ! all work perfectly ! I would share my setup in the coming days ! I still made ​​many test!

compared to the shadow of improvement for multi-server management while fonctionera since config.dtsd file so each server will have its own database ?

the integration of a shadow.dtsd updatebase variable for the update shadow pourais added a small asset! if that would avoid the duty of every customer retelechargée and reinstalled the basis of the script ( this obtion may be established if the case I did not view = (sorry )

cordially ELstringer

**Comment by danny-may** [comment]
Currently there is no way to migrate data from dtsd to shadow besides manual database manipulation. However this is most likely going to be needed, so i (or doomsider) will work on a data transfer script soon.
