### ISSUE TITLE
Garage timer

### ISSUE THREAD

**Issue by Jdehler** [doomsider/shadow#4]
The game's own built in spawn delay should trigger fine and limit possible abuse but placing an additional admin configurable limit with its own error (before it passes the command to the server) would be helpful.

Additionally; Suppressing the server's error message (IF invoked when calling for a ship too soon) and replacing it with message that's more contextual would be nice. This would be especially useful if a newbie owner or admin sets the delay too fast. Anything faster than the server's cool down.. And is wondering why they can't get their ships.

**Comment by doomsider** [comment]
Yeah this makes sense.  In the core command there is an idea for a simple cooldown command that basically sets unix time to the player database and then checks that against current unix time to make sure the proper amount of time has passed.  Likely in the future this type of system should be expanded to its own module as many commands could benefit from a cooldown.

**Comment by doomsider** [comment]
I am closing this issue for now since it is a planned feature.
