### ISSUE TITLE
when using the new setup process it doesnt put the m after he min max sizes.

### ISSUE THREAD

**Issue by zuch0698o** [doomsider/shadow#7]
had to go into defaults.dtsd to add it after running setup

**Comment by doomsider** [comment]
Yes this is why the default value has a m after it.  This has been a problem in the past so I will look to a solution to address it

**Comment by zuch0698o** [comment]
oh no i mean if you went through setup properly even putting say 2048m the default.dtsd folder only reflected 2048 when it should be 2048m

**Comment by zuch0698o** [comment]
so after playing aroun it was user error on this side
